<a href="https://colab.research.google.com/github/srabani-khuntia/LLM_Using_Python/blob/main/12_June.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [5]:
import numpy as np

arr1 = np.array([1,2,3]) #1D array from a list
arr2 = np.array([[1,2],[3,4]]) #2D array from a list of lists
arr3 = np.array((5,6,7)) #1D array from tuple

print(arr1)
print(arr2)
print(arr3)

[1 2 3]
[[1 2]
 [3 4]]
[5 6 7]


In [6]:
#create a 2x3 array of zeroes
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# create 3x2 array of ones
arr = np.ones((3,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
# create array with all elements 8
arr = np.full((2,2), 9)
arr

array([[9, 9],
       [9, 9]])

In [9]:
#array with elements from 10-19 with a step of 2
arr = np.arange(10,20,2)
arr

array([10, 12, 14, 16, 18])

In [10]:
# array with 5 evenly spaced numbers from 0 to 1
arr = np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
#2x3 array of random numbers between 0 and 1
arr = np.random.rand(2,3)
arr

array([[0.09686204, 0.70095283, 0.61530626],
       [0.20789729, 0.56705301, 0.69014531]])

## **Indexing and slicing**

In [12]:
#Same as lists

### **Broadcasting**

In [13]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr2 = np.array([10,20,30])

result = arr1 +arr2
print(result)

#Due to broadcasting, no need to worry if both the array dimensions are same or not. Numpy handles this through broadcasting

[[11 22 33]
 [14 25 36]]


## **Vectorisation**

In [15]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

#loops are not required

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


## **Universal Functions**

In [16]:
arr = np.array([0, np.pi/2, np.pi])

print(np.sin(arr))
print(np.cos(arr))
print(np.exp(arr))
print(np.log(arr))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 1.          4.81047738 23.14069263]
[      -inf 0.45158271 1.14472989]


/tmp/ipykernel_677/2605621185.py:6: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))


## **Linear Algebra**

In [18]:
A = np.array([[1,2],
             [3,4]])
b = np.array([5,6])

x = np.linalg.solve(A,b)
print(x)

[-4.   4.5]


## **Random Number Generation**

In [19]:
#required for stimulation and stochastic algorithms, to test on the data

random_array = np.random.rand(2,3) #2x3 array of random numbers between 0 and 1
print(random_array)


[[0.80881555 0.40649179 0.57444043]
 [0.17865597 0.1134667  0.20309502]]


## **Fourier Transforms**

In [20]:
#used to get the relevent data to be used in a project
# np.fft.fft - function used

signal = np.array([0,1,0,-1])
transformed_signal = np.fft.fft(signal)
print(transformed_signal)

[0.+0.j 0.-2.j 0.+0.j 0.+2.j]


## **Advanced indexing and slicing techniques**



1.   Boolean indexing
2.   Fancy indexing



In [ ]:
# if we look beyond the basic operations, it filters the conditions

In [23]:
#Boolean indexing
arr = np.array([1,2,3,4,5])
mask = arr > 2
print(arr[mask])

[3 4 5]


In [22]:
#Fancy indexing
arr = np.array([10,20,30,40,50])
indices = np.array([1,3])
print(arr[indices])

[20 40]


## **Performance Optimisation**


*  Avoiding Copies
*  Memory Management



In [26]:
#avoiding copies - view minimizes overhead association of copying data.

arr = np.array([1,2,3])
arr_view = arr.view()
arr_view

array([1, 2, 3])

In [27]:
#memory management - np.resize() or arr.resize - allocates or optimizes the memory

## **File I/O**

In [30]:
#methods to save and load arrays from disk efficiently - in .npy format
arr = np.array([1,2,3])
np.save('array.npy', arr)

loaded_arr = np.load('array.npy')
print(loaded_arr)

[1 2 3]


# **Numpy In Machine Learning**

## **Feauture scaling**



*   np.mean(data, axis=0) - computes the mean along each column of data
*   np.std(data, axis=0) - calculates the standard deviation along each column of data
*   (data - np.mean(data, axis=0)) / np.std(data, axis=0)- performs the scaling operation ensuring each feature in scaled_data has a mean of 0 and a standard deviation of 1

In [32]:
data = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
scaled_data = (data - np.mean(data, axis=0)) / (np.std(data, axis=0))
print(scaled_data)

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


## **Data manipulation**

In [33]:
import numpy as np

#Original data
data = np.array([[1,2,3],
                 [4,5,6]])

#Reshaping
reshaped_data = data.reshape(3,2) #change to a 3x2 array
print("reshaped data: \n", reshaped_data)

#Transposing
transposed_data = data.T #swap rows and columns
print("\nTransposed data: \n", transposed_data)

#Flattening
flattened_data = data.flatten() #convert to a 1D array
print("\nFlattened data: \n", flattened_data)

reshaped data: 
 [[1 2]
 [3 4]
 [5 6]]

Transposed data: 
 [[1 4]
 [2 5]
 [3 6]]

Flattened data: 
 [1 2 3 4 5 6]
